chains:
  # Example chain configuration with connection via smoldot
  - polkadot:
      validators:
        - stash: "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"
          # host_rpc: 127.0.0.1:9944 # optional, used in curl RPC calls and falls back to 127.0.0.1:9944
          ssh: # optional, if configured all commands are executed via SSH, otherwise local
            host: 192.0.2.100
            user: suno_user
            # port: 22 # optional, default 22
            # identity: "~/.ssh/id_ed25519" # optional, falls back to SSH agent
          commands:
            - name: "Rotate and Set keys"
              uses: "calls/rotate_and_set_keys"

            - name: "Has session keys"
              uses: "calls/has_keys"

            - name: "Has queued session keys"
              uses: "calls/has_queued_keys"

            - name: "Restart service"
              cmd: /restart
              run: "systemctl restart the-node-01.service"

            - name: "Upgrade node binary"
              cmd: /upgrade {version}
              run: "~/update_stable_node.sh {version}"

  - asset_hub_polkadot:
      signer:
        proxy_account: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"

  - people_polkadot:

  # Example chain configuration with connection via Trusted RPCs
  # - kusama:
  #     rpc_url: "ws://192.0.2.1:9944"
  #     validators:
  #       - "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"
  #
  # - asset_hub_kusama:
  #     rpc_url: "ws://192.0.2.2:9944"
  #
  # - people_kusama:
  #     rpc_url: "ws://192.0.2.3:9944"
  #
  # - paseo:
  #     rpc_url: "ws://192.0.2.1:9944"
  #     validators:
  #       - "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"
  #
  # - asset_hub_paseo:
  #     rpc_url: "ws://192.0.2.2:9944"
  #
  # - people_paseo:
  #     rpc_url: "ws://192.0.2.3:9944"
  #
  # - westend:
  #     rpc_url: "ws://192.0.2.1:9944"
  #     validators:
  #       [
  #         "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n",
  #         "5CJAQ9hr8ycTWgjYpErmC8pmr5rVE5XA6qZkFh4UQvAofdQ2",
  #       ]
  #       # - stash: "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"
  #       #   commands:
  #       #     - name: "test"
  #       #       run: "echo test"
  #
  # - asset_hub_westend:
  #     rpc_url: "ws://192.0.2.2:9944"
  #     # collators:
  #     #   - "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"

features:
  enable_validators: true
  show_nominators_counter: true # default true
  show_nominators_stake: true # default true
  show_own_stake: true # default true
  show_commission: false # default false
  show_payee: true # default true
  show_keys: true # default true

themes:
  active: "Suno Dark" # Builtin themes: ["Suno Dark", "Suno Light"]
  path: "themes"

# signer: # global signer configuration, overridden by chain-specific signer config
#  proxy_path: ".proxy_private.json"

explorer:
  url: "https://polkadot.js.org/apps/?rpc=wss://{chain}.rpc.turboflakes.io#/explorer/query/{block_hash}"
  # A few other explorers commented out below
  # url: "https://dev.papi.how/explorer/{block_hash}#networkId=localhost&endpoint=wss://{chain}.rpc.turboflakes.io"
  # url: "https://polkadot.chainconsole.com/apps/?rpc=wss://{chain}.rpc.turboflakes.io#/explorer/query/{block_hash}"
