chains:
  - polkadot:
      rpc_url: "ws://10.10.10.1:9944"
      light_client: false
      validators:
        - "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"
  - asset_hub_polkadot:
      rpc_url: "ws://10.10.10.2:9944"
      light_client: false

  - people_polkadot:
      rpc_url: "ws://10.10.10.3:9944"
      light_client: false

  # - kusama:
  #     rpc_url: "ws://10.10.20.1:9944"
  #     light_client: false
  #     validators:
  #       - "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"
  # - asset_hub_kusama:
  #     rpc_url: "ws://10.10.20.2:9944"
  #     light_client: false
  # - people_kusama:
  #     rpc_url: "ws://10.10.20.3:9944"
  #     light_client: false

  # - paseo:
  #     rpc_url: "ws://10.10.30.1:9944"
  #     light_client: false
  #     validators:
  #       - "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"
  # - asset_hub_paseo:
  #     rpc_url: "ws://10.10.30.2:9944"
  #     light_client: false
  # - people_paseo:
  #     rpc_url: "ws://10.10.30.3:9944"
  #     light_client: false

  # - westend:
  #     rpc_url: "ws://10.10.40.1:9944"
  #     light_client: false
  #     validators:
  #       [
  #         "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n",
  #         "5CJAQ9hr8ycTWgjYpErmC8pmr5rVE5XA6qZkFh4UQvAofdQ2",
  #       ]
  #       # - stash: "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"
  #       #   commands:
  #       #     - name: "test"
  #       #       run: "echo test"
  # - asset_hub_westend:
  #     rpc_url: "ws://10.10.40.2:9944"
  #     light_client: false
  #     # collators:
  #     #   - "5GTD7ZeD823BjpmZBCSzBQp7cvHR1Gunq7oDkurZr9zUev2n"

features:
  enable_validators: true
  enable_collators: false
  enable_rpcs: false

themes:
  active: "Suno Dark" # Builtin themes: ["Suno Dark", "Suno Light"]
  path: "themes"

signer:
  proxy_path: ".proxy_private.json"

explorer:
  url: "https://polkadot.js.org/apps/?rpc=wss://{chain}.rpc.turboflakes.io#/explorer/query/{block_hash}"
  # NOTE: Other explorers
  # url: "https://dev.papi.how/explorer/{block_hash}#networkId=localhost&endpoint=wss://{chain}.rpc.turboflakes.io"
  # url: "https://polkadot.chainconsole.com/apps/?rpc=wss://{chain}.rpc.turboflakes.io#/explorer/query/{block_hash}"
