[workspace]
members = [
    "packages/snops",
    "packages/tui",
    # "packages/chains/westend"
]

[workspace.package]
name = "snops"
version = "0.1.0"
authors = ["paulo <paulo@turboflakes.io>"]
license = "MIT or Apache-2.0"
repository = "https://github.com/turboflakes/snops"
description = "Just another way of managing substrate node operations in the Polkadot ecoystem."
edition = "2021"

[workspace.dependencies]
snops = { path = "packages/snops" }
snops-tui = { path = "packages/tui" }
# snops-westend = { path = "packages/chains/westend" }
resolver = "2"
