[workspace]
members = [
    "packages/actions",
    "packages/config",
    "packages/error",
    "packages/primitives",
    "packages/signer",
    "packages/suno",
    "packages/tui",
    "packages/chains/asset-hub-paseo",
    "packages/chains/asset-hub-polkadot",
    "packages/chains/asset-hub-kusama",
    "packages/chains/asset-hub-westend",
    "packages/chains/paseo",
    "packages/chains/polkadot",
    "packages/chains/kusama",
    "packages/chains/westend",
    "packages/chains/people-paseo",
    "packages/chains/people-polkadot",
    "packages/chains/people-kusama",
    "packages/chains/people-westend",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["paulo <paulo@turboflakes.io>"]
license = "Apache-2.0"
repository = "https://github.com/turboflakes/suno"
description = "Yet another way to manage Substrate Node Operations from your terminal."
edition = "2021"

[workspace.dependencies]
arboard = "3.6.1"
async-recursion = "1.0"
async-trait = "0.1.89"
color-eyre = "0.6.3"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.31"
hex = "0.4"
indoc = "2"
lazy_static = "1.5"
log = "0.4"
ratatui = "0.29.0"
regex = "1.11"
scale-encode = "0.10.1"
scale-info = "2.11.6"
secrecy = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
serde_yaml = "0.9"
sp-arithmetic = "28.0.0"
sp-core = "39.0.0"
strum = { version = "0.26.3", features = ["derive"] }
# subxt = { version = "0.50.0", features = ["reconnecting-rpc-client"] }
# subxt-signer = { version = "0.50.0", features = ["polkadot-js-compat"] }
# subxt-rpcs = { version = "0.50.0" }
# subxt = { git = "https://github.com/paritytech/subxt", features = ["reconnecting-rpc-client"] }
# subxt-signer = { git = "https://github.com/paritytech/subxt", package = "subxt-signer", features = ["subxt", "polkadot-js-compat"] }
# subxt-rpcs = { git = "https://github.com/paritytech/subxt", package = "subxt-rpcs", features = ["subxt"] }
subxt = { git = "https://github.com/turboflakes/subxt", branch = "pm-fix-latest", features = ["reconnecting-rpc-client"] }
subxt-signer = { git = "https://github.com/turboflakes/subxt", package = "subxt-signer", branch = "pm-fix-latest", features = ["subxt", "polkadot-js-compat"] }
subxt-rpcs = { git = "https://github.com/turboflakes/subxt", package = "subxt-rpcs",branch = "pm-fix-latest" }
tempfile = "3.2"
thiserror = "2.0"
tokio = { version = "1.43.0", features = ["full"] }
tui-logger = "0.14"
unicode-width = "0.2.0"
zeroize = { version = "1.7", features = ["derive"] }
