color_00 = "#141414"
color_01 = "#c06d44"
color_02 = "#afb97a"
color_03 = "#c2a86c"
color_04 = "#44474a"
color_05 = "#b4be7c"
color_06 = "#778385"
color_07 = "#ffffd4"
color_08 = "#404040"
color_09 = "#de7c4c"
color_10 = "#ccd88c"
color_11 = "#e2c47e"
color_12 = "#5a5e62"
color_13 = "#d0dc8e"
color_14 = "#8a989b"
color_15 = "#ffffd4"
background = "#141414"
foreground = "#ffffd4"
cursor_color = "#ffffff"
cursor_text = "#000000"
selection_background = "#313131"
selection_foreground = "#ffffd4"
